# Force Node 20 and ensure devDependencies are installed for Nuxt build
[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node .output/server/index.mjs"